### ISSUE TITLE
Is it worth encouraging isort? 

### ISSUE THREAD

**Issue by maffettone** [NSLS-II/scientific-python-cookiecutter#113]
While linting away unused imports is already done in the pre-commit stage, and in CI, I've had a few projects where the team preferred to also use isort to automatically sort imports. 
https://pycqa.github.io/isort/index.html
Are there opinions about this in either direction? Is it worth putting together a brief PR that puts an isort call in the pre-commit? It would behave much like black, and can eventually be added to #105 for CI.

**Comment by mrakitin** [comment]
I like that. I added it to the pre-commit hook in https://github.com/BNL-ATF/ophyd-basler/pull/6, and it works pretty well!
