### ISSUE TITLE
Add some documentation on environments.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/scientific-python-cookiecutter#16]
We currently advise the user:

> Verify that you have Python 3.6+. [...] If necessary, install it by your method of choice (apt, Homebrew, conda, etc.).

We are effectively trusting users who already know about environments to manage them themselves, and consigning uninformed users to system Python or standard package managers.

## Should we also advise them to do their work in some kind of environment?

I am becoming convinced yes, but I'm not completely sure yet whether we should lead with this --- presenting it as a prerequisite --- or consign it to an appendix. I would be convinced we should lead with it if we can present it succinctly.

## Which tool to recommend?

There are [many](https://stackoverflow.com/a/41573588/1221924), and it feels like an unstable, or at best only-recently stable, space.

At NSLS-II, we guide users to conda, but this repo is very intentionally more general than NSLS-II or synchrotrons. I hope to attract users and contributors from the scipy community at large, so there will be no mention of deployment details specific to NSLS-II (or of bluesky/databroker).

I think a lighter solution is best, to start. My present thinking is that venv (built-in) and pipenv (well-regarded) are strong candidates. Conda is also worth considering.

This is an _opinionated_ tutorial, aiming to streamline the process for a scientist who might not yet have encountered or appreciated the need for all this tooling, so we should clearly recommend one solution and then at most _mention_ others.

attn @ronpandolfi

**Comment by CJ-Wright** [comment]
I think the main case for conda is that it a) works as expected most of the time, b) will continue to work as expected most of the time, c) is how many people get their python (via the anaconda distribution) so extending it makes sense, d) works across languages. As a bonus (if we are being opinionated) conda packaging systems (conda-forge, bioconda, etc.) have standards that packages must pass to be inside the ecosystem and are very open to beginners. (I could potentially go on, esp. about the community around the conda packaging system).

**Comment by ronpandolfi** [comment]
Exactly what I had in mind, @danielballan . I agree that usage instructions for a specific tool should be included. I would vote for `venv` as my first choice. While @CJ-Wright makes an excellent case for conda as development platform, I'm less convinced that it is advantaged over `venv` in the context of an introductory course/walkthrough. There is more depth to conda as a platform than is necessary for a beginner, when the vanilla solution could suffice. 

Similarly, `pipenv` looks very fancy, but is functionally a magicky convenience. I would prefer offering an understanding of more fundamental tools first.

**Comment by CJ-Wright** [comment]
I would advise not to go with the system python. That could lead to issues is something goes sideways.

**Comment by tacaswell** [comment]
I'll put in a vote for `venv`.

To first order `python -mvenv my_hack_env; . my_hack_env/bin/activate; pip install ...` should just work on any python3 system (no matter how it was installed) for most of the scientific stack.

Further, everywhere else we are installing _anything_ we are using `pip` (the default install instructions, the source install instructions, everywhere on travis, ...), it seems odd to push conda as the *one true package manager*.  I also do not think we include any instructions on how configure a conda package?  The benefits of the conda eco-system do not show up until you have package lots of c or install things that are not well packaged on pypi etc.

Should definitely mention conda / include links, but not as the first option for virtual environments.

**Comment by danielballan** [comment]
I agree with the consensus on venv and the reasons stated for it. The case for pushing conda immediately would have been stronger in the days before we had wheels and a good built-in environment manager.

I will put up a draft with venv usage in line, linking an appendix with conda usage and some context for where “upgrading” to conda is useful.

**Comment by danielballan** [comment]
PS Thanks for your input, CJ. Would you be up for writing two or three sentences about what a conda forge feedstock is, why you would write one — with a link to relevant CF docs?

**Comment by CJ-Wright** [comment]
Sure

**Comment by CJ-Wright** [comment]
On a related note, you might look at [rever](https://regro.github.io/rever-docs/) I imagine that combined with cookiecutter one would have a one stop shop for project provisioning and releasing. (rever provides single command releasing, which can have interopt with versioneer if desired)
