### ISSUE TITLE
Link out to conda-forge docs

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/scientific-python-cookiecutter#32]
@CJ-Wright Is there a good landing page along the lines of, "So you want create a conda-forge feedstock...."?

**Comment by CJ-Wright** [comment]
Does this work? https://conda-forge.org/#add_recipe

**Comment by danielballan** [comment]
Perfect. Thanks!

**Comment by CJ-Wright** [comment]
No problem. Thanks for including us!
