### ISSUE TITLE
Licence makes my project copyright Brookhaven Science Associates

### ISSUE THREAD

**Issue by claresloggett** [NSLS-II/scientific-python-cookiecutter#42]
Most files initialised in a cookie-cut project are either generic or are configured by the cookiecutter setup, but the LICENSE file provided reads 

    Copyright (c) 2015, Brookhaven Science Associates, Brookhaven National Laboratory. All rights reserved.

and also mentions Brookhaven further down. I assume this is an oversight and the LICENSE file was intended to also be a template.

A good option might be to use the author name provided during configuration?

**Comment by tacaswell** [comment]
Also the year...

**Comment by danielballan** [comment]
Hi Clare! Yes, this was an accidental stowaway on a copy/paste from a Brookhaven project. We should be using the author and year from the cookiecutter config. Thanks for flagging this!

**Comment by tacaswell** [comment]
addressed on #46

**Comment by danielballan** [comment]
We fixed this in the wrong place, as noted by @MikeHart85. The license for _this cookiecutter_ should be BNL, but the license created by the cookiecutter should be templated.

**Comment by MikeHart85** [comment]
Not the wrong place, just missed a couple of BNL references. Making a PR to address this.
