### ISSUE TITLE
Can default year be the current year?

### ISSUE THREAD

**Issue by jklynch** [NSLS-II/scientific-python-cookiecutter#57]
The default year is 2018. Can this be handled programmatically?

**Comment by mrakitin** [comment]
https://stackoverflow.com/a/30071999 can help.

**Comment by danielballan** [comment]
And https://github.com/cookiecutter/cookiecutter/issues/155

**Comment by danielballan** [comment]
Suggestion from @klauer we should keep track of as well: https://github.com/NSLS-II/scientific-python-cookiecutter/pull/59#issuecomment-509290468

The closing of this issue was a heuristics misfire.

**Comment by mrakitin** [comment]
It was addressed via #105.
